"""
UBW Weekly Research Digest — board game mechanics and lore inspiration.

Fetches recent posts from r/boardgamedesign, r/tabletopgamedesign, and r/boardgames
via RSS, passes content to Claude for analysis, and emails the digest.

Schedule: 14:00 UTC every Monday (9:00 AM Lima / PET)
Recipients: xboredgaming@gmail.com, unlimitedboredworks@gmail.com
Run manually: python tools/weekly_research_digest.py
"""

import os
import re
import smtplib
import sys
import xml.etree.ElementTree as ET
from datetime import date, datetime, timedelta, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import parsedate_to_datetime

import anthropic
import requests
from dotenv import load_dotenv

load_dotenv()

RECIPIENTS = ["xboredgaming@gmail.com", "unlimitedboredworks@gmail.com"]

REDDIT_FEEDS = [
    ("boardgamedesign",    "https://www.reddit.com/r/boardgamedesign/hot/.rss"),
    ("tabletopgamedesign", "https://www.reddit.com/r/tabletopgamedesign/hot/.rss"),
    ("boardgames",         "https://www.reddit.com/r/boardgames/hot/.rss"),
]

GAMES = [
    ("To Be The One",    "cosmic/philosophical — epic tone"),
    ("Dead Man's Tide",  "pirate adventure — treachery tone"),
    ("Ashen Kingdom",    "dark fantasy — grim political tone"),
    ("High Noon Saloon", "western — tense cunning tone"),
]


# ---------------------------------------------------------------------------
# RSS Fetching
# ---------------------------------------------------------------------------

def _strip_html(text: str) -> str:
    text = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def fetch_reddit_feed(subreddit: str, feed_url: str, limit: int = 25) -> list[dict]:
    """Return recent hot posts from a subreddit (last 7 days)."""
    headers = {"User-Agent": "UBW-Research-Bot/1.0 (board game studio research)"}
    try:
        resp = requests.get(feed_url, headers=headers, timeout=20)
        resp.raise_for_status()
    except Exception as e:
        print(f"[digest] Failed to fetch {subreddit}: {e}", file=sys.stderr)
        return []

    since = datetime.now(timezone.utc) - timedelta(days=7)
    posts = []

    try:
        root = ET.fromstring(resp.text)
    except ET.ParseError as e:
        print(f"[digest] XML parse error for {subreddit}: {e}", file=sys.stderr)
        return []

    content_ns = "http://purl.org/rss/1.0/modules/content/"

    for item in root.iter("item"):
        title   = item.findtext("title", "").strip()
        link    = item.findtext("link", "").strip()
        pub_str = item.findtext("pubDate", "")

        # Skip if older than 7 days
        try:
            pub_date = parsedate_to_datetime(pub_str)
            if pub_date.tzinfo is None:
                pub_date = pub_date.replace(tzinfo=timezone.utc)
            if pub_date < since:
                continue
        except Exception:
            pass  # Include if date is unparseable

        raw = item.findtext(f"{{{content_ns}}}encoded", "") or item.findtext("description", "")
        text = _strip_html(raw)[:600]

        if title and link:
            posts.append({
                "title":      title,
                "url":        link,
                "text":       text,
                "subreddit":  subreddit,
            })

        if len(posts) >= limit:
            break

    return posts


def gather_posts() -> list[dict]:
    all_posts = []
    for subreddit, url in REDDIT_FEEDS:
        print(f"[digest] Fetching r/{subreddit}...")
        posts = fetch_reddit_feed(subreddit, url)
        all_posts.extend(posts)
        print(f"  -> {len(posts)} recent posts")
    return all_posts


# ---------------------------------------------------------------------------
# Digest Composition
# ---------------------------------------------------------------------------

def compose_digest(posts: list[dict], week_date: str) -> str:
    if not posts:
        return (
            f"# UBW Weekly Research Digest\n"
            f"*Week of: {week_date}*\n\n"
            "No relevant posts found this week. Try again next Monday.\n\n"
            "*Generated by UBW Research Agent*"
        )

    games_context = "\n".join(f"- {name}: {desc}" for name, desc in GAMES)

    posts_text = []
    for p in posts[:40]:  # cap at 40 posts to stay within token budget
        posts_text.append(
            f"[r/{p['subreddit']}] {p['title']}\nURL: {p['url']}\n{p['text']}"
        )
    posts_block = "\n\n---\n\n".join(posts_text)

    prompt = f"""You are a research assistant for Unlimited Board Works, a small bootstrapped board game studio in Lima, Peru.

Games in development:
{games_context}

Below are recent posts from board game design communities. Analyze them and produce the weekly research digest.

POSTS:
{posts_block}

Produce the digest in EXACTLY this format — no deviation:

---
# UBW Weekly Research Digest
*Week of: {week_date}*

## Mechanic Ideas

| Idea | How it works | Source URL | Best fit |
|---|---|---|---|
[fill rows — at least 3, max 8. Only include genuinely interesting mechanics. Never fabricate.]

### Notable finds
[2-3 sentences on the most interesting mechanic finds this week]

---

## Lore Inspiration

| Hook | Description | Source URL | Best fit |
|---|---|---|---|
[fill rows — at least 3, max 8. Only include genuinely useful lore/worldbuilding hooks. Never fabricate.]

### Notable finds
[2-3 sentences on the most interesting lore finds this week]

---

## Top 3 Recommendations
1. [Most actionable finding and why — one sentence]
2. [Second most actionable — one sentence]
3. [Third most actionable — one sentence]

---
*Generated by UBW Research Agent*
---

Rules:
- Only report what actually exists in the posts above. Never invent sources or URLs.
- If a category has fewer than 3 real results, say so honestly rather than padding.
- Keep each table row concise — idea name, how it works in 10-15 words, URL, best-fit game.
- "Best fit" must be one of: To Be The One, Dead Man's Tide, Ashen Kingdom, High Noon Saloon, or All."""

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text.strip()


# ---------------------------------------------------------------------------
# Email delivery
# ---------------------------------------------------------------------------

def send_digest(subject: str, body: str) -> bool:
    sender   = os.environ["GMAIL_SENDER"]
    password = os.environ["GMAIL_APP_PASSWORD"].replace(" ", "")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = sender
    msg["To"]      = ", ".join(RECIPIENTS)
    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=15) as smtp:
            smtp.login(sender, password)
            smtp.sendmail(sender, RECIPIENTS, msg.as_string())
        print(f"[digest] Sent to {', '.join(RECIPIENTS)}: {subject}")
        return True
    except Exception as e:
        print(f"[digest] Failed to send: {e}", file=sys.stderr)
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    week_date = date.today().strftime("%Y-%m-%d")
    subject   = f"UBW Weekly Research Digest — {week_date}"

    posts = gather_posts()
    print(f"[digest] Total posts collected: {len(posts)}")

    print("[digest] Composing digest with Claude...")
    body = compose_digest(posts, week_date)

    success = send_digest(subject, body)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
